spring:
  profiles:
    active: dev
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 15s
    config:
      uri: http://127.0.0.1:8888 
  health:
    sensitive: false
hello:
  world: localvalue

  
  
  